const MenuNavigation = {
  DATA: "DADOS",
  MEMBERS: "MEMBROS",
  VISITORS: "VISITANTES",
  REGISTER: "CADASTRAR",
  REGISTER_MEMBERS: "CADASTRAR MEMBROS",
  REGISTER_USERS: "CADASTRAR USUÁRIOS",
  PENDING: "AGUARDANDO APROVAÇÃO",
  DETAILS: "DETALHES",
};

export default MenuNavigation;
